name: Run Python Script

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'


      - name: Run Python file
        run: |
          echo "Running all Python scripts in the repo..."
          mkdir -p output
          for file in $(find . -name "*.py"); do
            echo "▶ Running $file" | tee -a output/log.txt
            python "$file" >> output/log.txt 2>&1
          done

      - name: Upload output as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-script-logs
          path: output/
